---
- name: Install nginx and uWSGI for a Python web application (pyweb)
  hosts: nginx-uwsgi
  become: yes
  become_user: root

# talk to all hosts just so we can learn about them
- hosts: all
  tasks:
     - group_by: key=os_{{ ansible_distribution }}


- hosts: os_CentOS
  gather_facts: False
  become: yes
  become_user: root
  roles:
#      - install_CentOS
     - setup_venv_app
     - patch_config_CentOS_Fedora
     - configure_nginx_uwsgi
     - start_services
