---
- name: Install EPEL (CentOS)
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install packages (CentOS)
  yum:
    name: python27,python27-pip,uwsgi,uwsgi-plugin-python2,uwsgi-logger-file,nginx,git,wget
    state: present
    update_cache: yes

- name: Install virtualenv for root (CentOS)
  command: python3 -m pip install --user virtualenv
